name: "Run Tests"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1, 8.0, 7.4, 7.3]
        laravel: [10.*, 9.*, 8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.23
        exclude:
            - laravel: 10.*
              php: 8.0
            - laravel: 10.*
              php: 7.4
            - laravel: 10.*
              php: 7.3
            - laravel: 9.*
              php: 8.2
              dependency-version: prefer-lowest
            - laravel: 9.*
              php: 7.4
            - laravel: 9.*
              php: 7.3
            - laravel: 8.*
              php: 8.2
              dependency-version: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -proot -e 'CREATE DATABASE test'
          mysql -uroot -proot -e "CREATE USER 'lara'@'%' IDENTIFIED WITH mysql_native_password BY 'lara'"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON test.* TO 'lara'@'%'"
          mysql -uroot -proot -e "FLUSH PRIVILEGES"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/database:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Setup .env
        run: |
          touch .env
          echo "DB_HOST=127.0.0.1"  >> .env
          echo "DB_PORT=3306"       >> .env
          echo "DB_DATABASE=test" >> .env
          echo "DB_USERNAME=lara"   >> .env
          echo "DB_PASSWORD=lara"   >> .env

      - name: Execute tests
        run: vendor/bin/phpunit
